apiVersion: apps/v1
kind: Deployment
metadata:
  name: spatial-service
  labels:
    app: spatial-service
spec:
  replicas: 1 # Adjust as needed
  selector:
    matchLabels:
      app: spatial-service
  template:
    metadata:
      labels:
        app: spatial-service
    spec:
      containers:
      - name: spatial-service
        image: spatial-service:latest
        ports:
          - containerPort: 3000
        env:
          - name: DB_HOST 
            value: spatial-service-db

