apiVersion: apps/v1
kind: Deployment
metadata:
  name: spatial-service-db
  labels:
    app: spatial-service-db
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: spatial-service-db
  template:
    metadata:
      labels:
        app: spatial-service-db
    spec:
      containers:
      - name: postgis
        image: postgis/postgis:14-3.3 # Example, adjust version as needed
        ports:
          - containerPort: 5432
        env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secret 
                key: postgres-password
        volumeMounts:
          - name: postgis-data 
            mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgis-data
          persistentVolumeClaim:
            claimName: postgres-pvc

